In [1]:
import numpy as np

In [6]:
#To print the values in a range
a = np.arange(100)

In [7]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [14]:
#Array with 2 Rows and 3 Columns
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# To get Array size
a = np.array([(1,2,3),(4,5,6)])

In [17]:
a.ndim

2

In [32]:
a = np.array([(2,4,6),(1,5,2),(4,5,9)])

In [34]:
# Indexing and Slicing   # a is defined in 32
a[1:2,2]

array([2])

In [35]:
# To Get Maximum value of the array # a is defined in 32
a.max()

9

In [36]:
# To Get Minimum value of the Array    # a is defined in 32
a.min()

1

In [40]:
# To get sum of the elements        # a is defined in 32
a.sum()

38

In [42]:
# To get sum of elements vertical in order        # a is defined in 32
a.sum(axis=0)

array([ 7, 11, 20])

In [43]:
# To get the sum of horizontal elements           # a is defined in 32
a.sum(axis=1)

array([12,  8, 18])

In [39]:
# To sort the elements of the array            # a is defined in 32
a.sort()

In [38]:
a

array([[2, 4, 6],
       [1, 2, 5],
       [4, 5, 9]])

In [44]:
a = np.array([(1,2,3),(4,5,6)])

In [45]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
# Square roots of elements in array
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [53]:
# Standard Deviation
np.std(a)

1.707825127659933

In [54]:
a = np.array([(1,2,3),(3,4,5)])
b = np.array([(1,2,3),(3,4,5)])

In [55]:
# Addition of Arrays
a+b

array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [56]:
# Difference between Arrays
a-b

array([[0, 0, 0],
       [0, 0, 0]])

In [57]:
# Multiplication of Arrays
a*b

array([[ 1,  4,  9],
       [ 9, 16, 25]])

In [58]:
#Division of Arrays
a/b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
# Modulus Division
a%b

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [66]:
a =([(1,2,3),(4,5,6)],[(2,4,6),(1,3,5)])

In [67]:
# Vertical View of the array
np.vstack(a)

array([[1, 2, 3],
       [4, 5, 6],
       [2, 4, 6],
       [1, 3, 5]])

In [68]:
# Horizontal view of the array
np.hstack(a)

array([[1, 2, 3, 2, 4, 6],
       [4, 5, 6, 1, 3, 5]])

In [3]:
import numpy as np

In [4]:
a = np.array([(1,2,3),(4,5,6)])

In [5]:
# Array elements concatenation
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [7]:
# To get the exponential values of Array elements
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [8]:
# To get logarithm Value
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])